### PR TITLE
Atbash cipher

### PR DESCRIPTION
**Pull request by cousinitt**
Happy Hacktoberfest ...

### CODE REVIEW

**Comment by guygastineau** [comment]
I don't have the rights to edit the title of this PR, but this is the `affine cipher` not `atbash`.

Also cheers 😁 I introduced this exercise to exercism, so I am always happy to see it on various tracks.

**Comment by cousinitt** [comment]
I guess I did mix some things up ... I'll see if I can unravel them.

**Comment by cousinitt** [comment]
I loved this exercise! Thanks for introducing it!

**Comment by guygastineau** [comment]
Thanks for loving it 💞

**Comment by cousinitt** [comment]
I'm not a Git pro yet, so I am probably just going to cancel this PR and start another one. I can't figure out how to extract the affine cipher stuff from this one ...

**Comment by guygastineau** [comment]
If the affine cipher commits are separate from the atbash commits, then they can be rebase out of it (after they have been plucked to another branch).

Your approach works too though.

**Pull request closed without merging**
