### PR TITLE
Twelve days

### PR DESCRIPTION
**Pull request by serialhex**
This isn't quite done yet, but I wanted to "stake my claim" as it were so nobody jumps ahead of me.  I'll post when I think it's done.

### CODE REVIEW

**Comment by robertpostill** [comment]
Thanks for posting the PR @serialhex 👍  Looking forward to seeing it evolve.

**Comment by serialhex** [comment]
I think it's (mostly) ready now.  I can add more tests if you like, but I think that testing the whole snog itself is enough for the problem spec, the rest is just fluff IMO.

If you want more ask and I'll add!

**Comment by serialhex** [comment]
@robertpostill this and the other pull requests I've opened are done! Please let me know if there is anything in this (or one of the others) you would like me to change.

**Review by kytrinyx — APPROVED** [review]
This looks great. I'm so sorry the PR never got properly reviewed and merged when you submitted it.

I've made some tweaks to bring it up to date with changes made to the platform in the past couple of years, and will merge it as soon as CI is green.

**Pull request merged**
