### PR TITLE
Version info

### PR DESCRIPTION
**Pull request by guygastineau**
This relates to #131 

I realized after I made the script that not all of the exercise tests have the version info in them, or perhaps they don't have it on a line that also includes the text `problem-specifications`.

I definitely think there should be some kind of standard for representation of the version info in the test files.  If this is done, then the script I wrote can be used to check for missing versions, and to automatically update the `.meta/version` files from the convention in the test files.

Let me know what you think.

### CODE REVIEW

**Comment by guygastineau** [comment]
So, I recently learned that `.meta/version` is not the only way to represent the version information to the Dashboard project, so if you all want to use4 another convention for it just let me know, and I will write some stuff to handle it.

**Comment by robertpostill** [comment]
I think it's great that you've taken the effort so I'm merging this.  If the approach has problems we can always fix it then right?

**Comment by guygastineau** [comment]
No problem.  I have work to do on both the bash and scheme tracks, but I like Racket (I started using it for some projects too :heart_eyes: ), so I figure it is a good idea to try helping out over here.

**Comment by robertpostill** [comment]
It's a lovely language 😄  but thanks for the help, always appreciated 👍

**Pull request merged**
