### PR TITLE
Armstrong numbers

### PR DESCRIPTION
**Pull request by cousinitt**
New, simple problem for the track.
Please let me know if you would like anything to be changed.

### CODE REVIEW

**Comment by cousinitt** [comment]
I have a couple of other simple problems that I have ready for pull requests (isogram, atbash-cipher, reverse-string) - but since I am a bit new to GitHub, I haven't figured out how to do multiple pull requests.

**Comment by robertpostill** [comment]
Sorry, took me a while to this.  But thanks.  Always nice to have problems added to the track.  Have you  considered becoming a maintainer?  We could do with the help if you're interested 😄

**Comment by robertpostill** [comment]
"I haven't figured out how to do multiple pull requests."  Generally you have a branch per change and each branch can be tied to a pull request.  Hope that helps 😄

**Comment by cousinitt** [comment]
Since you asked, I would like to be a maintainer :)
I think Racket is great - and I want to help make the Racket track the best
on the site!

**Pull request merged**
