### PR TITLE
Update instructions.md

### PR DESCRIPTION
**Pull request by hunkyjimpjorps**
being more explicit that "it" in this case is the function

### CODE REVIEW

**Comment by BNAndras** [comment]
Thanks for the PR, I'll take a look later this week.

**Comment by BNAndras** [comment]
Thanks for the PR. I'd be glad to accept it, but the `instructions.md` for that exercise comes from https://github.com/exercism/problem-specifications/blob/main/exercises/hello-world/description.md. That repo contains the shared metadata and documentation for all practice exercises on Exercism. If we make the edit here, it'll be overwritten the next time I sync the documentation from that repo. Therefore, I'd suggest making this PR in the problem-specifications repo instead. Then, all of Exercism's tracks can benefit from this potential change and it won't be overwritten by later syncs.

**Comment by hunkyjimpjorps** [comment]
The impetus for making this change was me showing Exercism to someone else in the Racket community, and them getting mad at the description for being misleading because they thought the correct answer would be something like `(println "Hello World")` based on a restrictive reading of "it".  I think I thought about that when I originally proposed that, but I decided to target it specifically to the track because I'm not familiar enough with all the other tracks to know if "the function" is the proper way to describe what's going on (for example, it might be a class method instead).  

I'll float it at a PR there and see what people say.

**Comment by BNAndras** [comment]
Yeah, it’s been a fairly common issue for students even with the recently added Hello World video. I think that PR will be well-received.

If they pass, I think it’s worth adding an instructions append section here which comes after the standard set of instructions. There, we can clarify it’s a function returning a value.
Another option I’m considering is that I recall the Python test runner having code specifically for testing hello-world that gives more specific error information about what’s expected. We could do something similarly here with the caveat it only helps students working online with our test runner.

**Comment by BNAndras** [comment]
@hunkyjimpjorps, would you be okay submitting a PR for an instructions append file for this exercise? See https://exercism.org/docs/building/tracks/practice-exercises#h-documentation-files. This would be specific to just Racket so you can clarify the "it" as a function. If you need an idea of what they look like, the Python track has several examples of instructions appends.

**Pull request closed without merging**
