### PR TITLE
Added more elegant example solution to reverse-string.

### PR DESCRIPTION
**Pull request by cousinitt**
I added @guygastineau's elegant suggestion from another comment thread. I hope that he doesn't mind.

### CODE REVIEW

**Comment by guygastineau** [comment]
I don't mind at all.

**Comment by guygastineau** [comment]
Do the other files from #119 also need to be added?

**Comment by cousinitt** [comment]
No - pull request 119 was closed, I re-opened it as pull request 124 and it
is now in the Racket track. I imagine that pull request 121 could be closed
...

**Comment by guygastineau** [comment]
Cool. I could have just checked I guess :rofl:   I'll approve this. but I am not a maintainer here.

**Pull request merged**
