### PR TITLE
reverse-string

### PR DESCRIPTION
**Pull request by cousinitt**
New exercise, reverse-string :)

### CODE REVIEW

**Comment by cousinitt** [comment]
?? Travis errors out because it can't log in as zenspider ?!

**Comment by zenspider** [comment]
1. Use @zenspider to notify on here, otherwise they don't see anything.
2. When emailing a person (instead of #1) links to actual details help.
3. Please rebase against master.

**Comment by zenspider** [comment]
@cousinitt hrm... I'm not sure what I just did. I pulled down your PR into a branch, rebased against master, and tried to push it back to you. For some reason, that closed this PR in a way that I can't just click "reopen".

I still have all your commits locally here, so I can merge them directly if need be.

**Comment by cousinitt** [comment]
@zenspider sorry for the email, I'm a bit new to GitHub. I just re-committed the exercise - I hope that didn't jack anything up.

**Pull request closed without merging**
