### PR TITLE
New Exercise: Sublist

### PR DESCRIPTION
**Pull request by czrpb**
Copied (from Elixir track) and implemented `Sublist` exercise. Also, quick fix to `matching-brackets` config.

### CODE REVIEW

**Comment by czrpb** [comment]
hmmm .. not understanding why these are failing: maybe racket version? looks like it is using 8.2 which is pretty old yes?

thoughts?

**Comment by ErikSchierboom** [comment]
What is the latest Racket version?

**Comment by czrpb** [comment]
8.6 i believe

**Comment by ErikSchierboom** [comment]
@czrpb Coincidentally, a PR was just merged to [upgrade the test runner to Racket 8.6](https://github.com/exercism/racket-test-runner/pull/54). Would you be willing to submit a (different) PR to update this repo to Racket 8.6?

**Comment by czrpb** [comment]
> @czrpb Coincidentally, a PR was just merged to [upgrade the test runner to Racket 8.6](https://github.com/exercism/racket-test-runner/pull/54). Would you be willing to submit a (different) PR to update this repo to Racket 8.6?

Check this PR: #236

Thoughts?

**Comment by ErikSchierboom** [comment]
@czrpb I've left one comment, but looks good!

**Comment by czrpb** [comment]
ugh .. finally replicated on my own sysem, so working on this.

**Comment by czrpb** [comment]
@ErikSchierboom -- whew! finally!

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
