### PR TITLE
Add (and fix) meetup

### PR DESCRIPTION
**Pull request by zenspider**
This is a fork of @mbertheau's submission and subsumes it.

### CODE REVIEW

**Comment by jgilray** [comment]
I'm pretty new here, but it looks like the format of ```config.json``` has changed.  I just ported a different exercise without problems.  Basically ```config.json``` should look like this:
```
{
  "language": "Racket",
  "active": true,
  "exercises": [
    {
      "uuid": "4fb471fc-4e6d-486d-abf5-939e89f028fc",
      "slug": "hello-world",
      "core": false,
      "unlocked_by": null,
      "difficulty": 1,
      "topics": [
        "optional values",
        "text formatting"
      ]
    },
    {
      "uuid": "b5b537d0-7c5d-45e5-af1d-b4da4f32514b",
      "slug": "grains",
      "core": false,
      "unlocked_by": null,
      "difficulty": 1,
      "topics": [

      ]
    },
...
    {
      "uuid": "b234225c-fcde-445f-9222-f80c25d0f499",
      "slug": "accumulate",
      "deprecated": true
    }
  ],
  "foregone": [

  ]
}
```
You can use ```configlet lint .``` to check the format

**Comment by yurrriq** [comment]
@jgilray, would you be willing and able to get this ready to merge?

**Comment by jgilray** [comment]
Yes @yurrriq.  I will help, but I will need some guidance:  How do I get the file from @zenspider's fork/branch?  Where do I commit/push my changes?  I've willing to learn more about git, but this is not something I've done before.  Thanks.

**Comment by yurrriq** [comment]
It goes a little something like this:

```fish
git checkout -b zenspider-mbertheau-fix-meetup master
git pull https://github.com/zenspider/xracket.git mbertheau-fix-meetup
# make changes
git commit -m 'fixed all the things'
git push -u origin mbertheau-fix-meetup
# open a new PR to exercism/racket master
```

**Comment by jgilray** [comment]
Hi @yurrriq, I think I can do this, but I will wait until the ```config.json``` issue in https://github.com/exercism/racket/pull/83 is resolved before I do it.

**Comment by jgilray** [comment]
OK, @yurrriq, I followed your instructions and added a PR.  I suppose this one can be closed?

**Comment by yurrriq** [comment]
Superseded by #87.

**Pull request closed without merging**
